version: "3.8"
services:
  web:
    build: ./app
    image: 672051635952.dkr.ecr.us-east-2.amazonaws.com/workshop2:workshop2_web ### REPLACE wih actual ECR URI
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres REPLACE   #########
      - DB_PASSWORD=admin123 REPLACE   ##########
      - DB_HOST=nctutorials.c5r6ke6mwmhp.us-east-2.rds.amazonaws.com REPLACE ### replace with actual DB host 
      - DB_PORT=5432
      - DATABASE=postgres
  nginx:
    build: ./nginx
    image: 672051635952.dkr.ecr.us-east-2.amazonaws.com/workshop2:workshop2_nginx ## REPLACE with actual ECR URI
    volumes:
      - static_volume:/usr/src/app/static REMOVE, NOT USING STATIC CONTENT
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: